<?php

namespace AppBundle\Repository;

/**
 * ApartmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApartmentRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByLimit($limit)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT a
                 FROM AppBundle:Apartment a
                 ORDER BY a.id ASC'
            )->setMaxResults($limit);

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
