# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    # recommended here: https://speakerdeck.com/nicolasgrekas/dependency-injection-component-v4-dot-0-symfonycon-cluj-2017
    container.autowiring.strict_mode: true
    container.dumper.inline_class_loader: true

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false